### ISSUE TITLE
Exception with Postgres BYTEA type

### ISSUE THREAD

**Issue by roganov** [koxudaxi/local-data-api#88]
local-data-api image: koxudaxi/local-data-api:0.5.4
PostgreSQL image: postgres:10.12-alpine

Given table such as
```sql
			CREATE TABLE IF NOT EXISTS events (
				id SERIAL PRIMARY KEY,
				rep VARCHAR(64),
				data BYTEA
			)
```
and a query such as
```sql
SELECT id, data FROM events
```
local-data-api throws this exception:
```
local-data-api_1  | 192.168.144.1:45132 - "POST /Execute HTTP/1.1" 500
local-data-api_1  | [2021-03-04 16:48:35 +0000] [7] [ERROR] Exception in ASGI application
local-data-api_1  | Traceback (most recent call last):
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
local-data-api_1  |     result = await app(self.scope, self.receive, self.send)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
local-data-api_1  |     return await self.app(scope, receive, send)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 140, in __call__
local-data-api_1  |     await super().__call__(scope, receive, send)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 134, in __call__
local-data-api_1  |     await self.error_middleware(scope, receive, send)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 178, in __call__
local-data-api_1  |     raise exc from None
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 156, in __call__
local-data-api_1  |     await self.app(scope, receive, _send)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 73, in __call__
local-data-api_1  |     raise exc from None
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 62, in __call__
local-data-api_1  |     await self.app(scope, receive, sender)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 590, in __call__
local-data-api_1  |     await route(scope, receive, send)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 208, in __call__
local-data-api_1  |     await self.app(scope, receive, send)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
local-data-api_1  |     response = await func(request)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 129, in app
local-data-api_1  |     raw_response = await run_in_threadpool(dependant.call, **values)
local-data-api_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 25, in run_in_threadpool
local-data-api_1  |     return await loop.run_in_executor(None, func, *args)
local-data-api_1  |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
local-data-api_1  |     result = self.fn(*self.args, **self.kwargs)
local-data-api_1  |   File "/app/local_data_api/main.py", line 99, in execute_statement
local-data-api_1  |     response: ExecuteStatementResponse = resource.execute(
local-data-api_1  |   File "/app/local_data_api/resources/jdbc/__init__.py", line 158, in execute
local-data-api_1  |     records=[
local-data-api_1  |   File "/app/local_data_api/resources/jdbc/__init__.py", line 159, in <listcomp>
local-data-api_1  |     [
local-data-api_1  |   File "/app/local_data_api/resources/jdbc/__init__.py", line 160, in <listcomp>
local-data-api_1  |     self.get_filed_from_jdbc_type(
local-data-api_1  |   File "/app/local_data_api/resources/jdbc/postgres.py", line 45, in get_filed_from_jdbc_type
local-data-api_1  |     return super().get_filed_from_jdbc_type(value, jdbc_type)
local-data-api_1  |   File "/app/local_data_api/resources/jdbc/__init__.py", line 97, in get_filed_from_jdbc_type
local-data-api_1  |     return Field(blobValue=b64encode(value))
local-data-api_1  |   File "/usr/local/lib/python3.8/base64.py", line 58, in b64encode
local-data-api_1  |     encoded = binascii.b2a_base64(s, newline=False)
local-data-api_1  | TypeError: a bytes-like object is required, not 'str'
```

**Comment by roganov** [comment]
OH this doesn't really support all cases because of https://github.com/baztian/jaydebeapi/issues/147.

**Comment by koxudaxi** [comment]
@roganov 
I have released a new version as `0.5.5`

> OH this doesn't really support all cases because of baztian/jaydebeapi#147.

OK, I feel good to resolve your issue. we would fix other cases in the next chance. 

Thank you very much!!

**Comment by roganov** [comment]
Thanks for merging and your work on this project!
Unfortunately I'm back to using native driver because of the issue I linked above.

**Comment by koxudaxi** [comment]
I got it.  I will tell you when the problem is fixed in some time 🚀
